---
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: amazon_linux_2014.03
    driver_plugin: ec2
    driver_config:
      image_id: ami-383a5008
      username: ec2-user
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
