---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 8080, host: 8080}]
  - ["forwarded_port", {guest: 8000, host: 8000}]

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: centos-6.4

suites:
  - name: smoke_tests
    run_list:
      - recipe[frog::database]
      - recipe[frog::server]
      - recipe[frog::nginx]
    attributes:
      mysql:
        server_root_password: frog
      frog:
        db:
          password: frog
          install_dbms: true
        debug: True
        settings:
          port: 80
          url: 'http://localhost'
          media_path: '/media/'
          static_path: '/static/'
        nginx:
          server_name: 'localhost'
  - name: server
    run_list:
      - recipe[frog::database]
      - recipe[frog::server]
    attributes:
      mysql:
        server_root_password: frog
      frog:
        db:
          password: frog
          install_dbms: true
        debug: True
        settings:
          url: 'http://localhost'
          port: 8000
          media_path: '/media/'
          static_path: '/static/'
  - name: database
    run_list:
      - recipe[frog::database]
    attributes:
      mysql:
        server_root_password: frog
      frog:
        db:
          install_dbms: true
          password: frog
  - name: nginx
    run_list:
      - recipe[frog::nginx]
    attributes:
      frog:
        settings:
          url: 'http://localhost'
        nginx:
          server_name: 'localhost'
  - name: server_rds_db
    run_list:
      - recipe[frog::server]
    attributes:
      frog:
        db:
          password: frogadmin
          host: <%= ENV['AWS_RDS_HOST'] %>
    excludes: ["ubuntu-14.04", "ubuntu-12.04", "centos-6.4"]
