name 'frog'
maintainer 'Nick Downs'
maintainer_email 'nickryand@gmail.com'
license 'MIT'
description 'Installs and configures the Frog Media Server'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '1.0.1'

depends 'database', '~> 2.2.0'
depends 'python', '~> 1.4.6'
depends 'openssl', '~> 1.1.0'
depends 'runit', '~> 1.5.10'
depends 'mysql', '~> 5.3.6'
depends 'gunicorn', '~> 1.1.6'
depends 'nginx', '~> 2.7.4'
depends 'chef-sugar', '~> 2.0.0'
depends 'yum', '~> 3.2.2'
depends 'build-essential', '~> 2.0.4'
depends 'apt', '~> 2.4.0'
